### ISSUE TITLE
sqlalchemy.exc.StatementError: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back

### ISSUE THREAD

**Issue by gustavofonseca** [scieloorg/doi_request#5]
```
2/2/2018 3:29:13 PM[2018-02-02 15:29:13,336: ERROR/ForkPoolWorker-8] Task tasks.celery.triage_deposit[740ebe60-c531-46fe-90d0-96b9ca90d36d] raised unexpected: StatementError("(sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back",)
2/2/2018 3:29:13 PMTraceback (most recent call last):
2/2/2018 3:29:13 PM  File "/usr/local/lib/python3.5/site-packages/SQLAlchemy-1.2.0b2-py3.5-linux-x86_64.egg/sqlalchemy/engine/base.py", line 1112, in _execute_context
2/2/2018 3:29:13 PM    conn = self.__connection
2/2/2018 3:29:13 PMAttributeError: 'Connection' object has no attribute '_Connection__connection'
2/2/2018 3:29:13 PM
2/2/2018 3:29:13 PMDuring handling of the above exception, another exception occurred:
2/2/2018 3:29:13 PM
2/2/2018 3:29:13 PMTraceback (most recent call last):
2/2/2018 3:29:13 PM  File "/usr/local/lib/python3.5/site-packages/SQLAlchemy-1.2.0b2-py3.5-linux-x86_64.egg/sqlalchemy/engine/base.py", line 1114, in _execute_context
2/2/2018 3:29:13 PM    conn = self._revalidate_connection()
2/2/2018 3:29:13 PM  File "/usr/local/lib/python3.5/site-packages/SQLAlchemy-1.2.0b2-py3.5-linux-x86_64.egg/sqlalchemy/engine/base.py", line 424, in _revalidate_connection
2/2/2018 3:29:13 PM    "Can't reconnect until invalid "
2/2/2018 3:29:13 PMsqlalchemy.exc.InvalidRequestError: Can't reconnect until invalid transaction is rolled back
2/2/2018 3:29:13 PM
2/2/2018 3:29:13 PMThe above exception was the direct cause of the following exception:
2/2/2018 3:29:13 PM
2/2/2018 3:29:13 PMTraceback (most recent call last):
2/2/2018 3:29:13 PM  File "/usr/local/lib/python3.5/site-packages/celery-4.1.0-py3.5.egg/celery/app/trace.py", line 374, in trace_task
2/2/2018 3:29:13 PM    R = retval = fun(*args, **kwargs)
2/2/2018 3:29:13 PM  File "/usr/local/lib/python3.5/site-packages/celery-4.1.0-py3.5.egg/celery/app/trace.py", line 629, in __protected_call__
2/2/2018 3:29:13 PM    return self.run(*args, **kwargs)
2/2/2018 3:29:13 PM  File "/app/tasks/celery.py", line 91, in triage_deposit
2/2/2018 3:29:13 PM    deposit = DBSession.query(Deposit).filter_by(code=code).first()
2/2/2018 3:29:13 PM  File "/usr/local/lib/python3.5/site-packages/SQLAlchemy-1.2.0b2-py3.5-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2776, in first
2/2/2018 3:29:13 PM    ret = list(self[0:1])
2/2/2018 3:29:13 PM  File "/usr/local/lib/python3.5/site-packages/SQLAlchemy-1.2.0b2-py3.5-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2568, in __getitem__
2/2/2018 3:29:13 PM    return list(res)
2/2/2018 3:29:13 PM  File "/usr/local/lib/python3.5/site-packages/SQLAlchemy-1.2.0b2-py3.5-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2876, in __iter__
2/2/2018 3:29:13 PM    return self._execute_and_instances(context)
2/2/2018 3:29:13 PM  File "/usr/local/lib/python3.5/site-packages/SQLAlchemy-1.2.0b2-py3.5-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2899, in _execute_and_instances
2/2/2018 3:29:13 PM    result = conn.execute(querycontext.statement, self._params)
2/2/2018 3:29:13 PM  File "/usr/local/lib/python3.5/site-packages/SQLAlchemy-1.2.0b2-py3.5-linux-x86_64.egg/sqlalchemy/engine/base.py", line 945, in execute
2/2/2018 3:29:13 PM    return meth(self, multiparams, params)
2/2/2018 3:29:13 PM  File "/usr/local/lib/python3.5/site-packages/SQLAlchemy-1.2.0b2-py3.5-linux-x86_64.egg/sqlalchemy/sql/elements.py", line 269, in _execute_on_connection
2/2/2018 3:29:13 PM    return connection._execute_clauseelement(self, multiparams, params)
2/2/2018 3:29:13 PM  File "/usr/local/lib/python3.5/site-packages/SQLAlchemy-1.2.0b2-py3.5-linux-x86_64.egg/sqlalchemy/engine/base.py", line 1053, in _execute_clauseelement
2/2/2018 3:29:13 PM    compiled_sql, distilled_params
2/2/2018 3:29:13 PM  File "/usr/local/lib/python3.5/site-packages/SQLAlchemy-1.2.0b2-py3.5-linux-x86_64.egg/sqlalchemy/engine/base.py", line 1121, in _execute_context
2/2/2018 3:29:13 PM    None, None)
2/2/2018 3:29:13 PM  File "/usr/local/lib/python3.5/site-packages/SQLAlchemy-1.2.0b2-py3.5-linux-x86_64.egg/sqlalchemy/engine/base.py", line 1402, in _handle_dbapi_exception
2/2/2018 3:29:13 PM    exc_info
2/2/2018 3:29:13 PM  File "/usr/local/lib/python3.5/site-packages/SQLAlchemy-1.2.0b2-py3.5-linux-x86_64.egg/sqlalchemy/util/compat.py", line 203, in raise_from_cause
2/2/2018 3:29:13 PM    reraise(type(exception), exception, tb=exc_tb, cause=cause)
2/2/2018 3:29:13 PM  File "/usr/local/lib/python3.5/site-packages/SQLAlchemy-1.2.0b2-py3.5-linux-x86_64.egg/sqlalchemy/util/compat.py", line 186, in reraise
2/2/2018 3:29:13 PM    raise value.with_traceback(tb)
2/2/2018 3:29:13 PM  File "/usr/local/lib/python3.5/site-packages/SQLAlchemy-1.2.0b2-py3.5-linux-x86_64.egg/sqlalchemy/engine/base.py", line 1114, in _execute_context
2/2/2018 3:29:13 PM    conn = self._revalidate_connection()
2/2/2018 3:29:13 PM  File "/usr/local/lib/python3.5/site-packages/SQLAlchemy-1.2.0b2-py3.5-linux-x86_64.egg/sqlalchemy/engine/base.py", line 424, in _revalidate_connection
2/2/2018 3:29:13 PM    "Can't reconnect until invalid "
2/2/2018 3:29:13 PMsqlalchemy.exc.StatementError: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back [SQL: 'SELECT deposit.code AS deposit_code, deposit.pid AS deposit_pid, deposit.issn AS deposit_issn, deposit.volume AS deposit_volume, deposit.number AS deposit_number, deposit.issue_label AS deposit_issue_label, deposit.journal AS deposit_journal, deposit.journal_acronym AS deposit_journal_acronym, deposit.collection_acronym AS deposit_collection_acronym, deposit.publication_year AS deposit_publication_year, deposit.xml_file_name AS deposit_xml_file_name, deposit.prefix AS deposit_prefix, deposit.doi AS deposit_doi, deposit.doi_batch_id AS deposit_doi_batch_id, deposit.is_xml_valid AS deposit_is_xml_valid, deposit.started_at AS deposit_started_at, deposit.updated_at AS deposit_updated_at, deposit.submission_xml AS deposit_submission_xml, deposit.submission_status AS deposit_submission_status, deposit.submission_updated_at AS deposit_submission_updated_at, deposit.submission_response AS deposit_submission_response, deposit.has_submission_xml_valid_references AS deposit_has_submission_xml_valid_references, deposit.feedback_xml AS deposit_feedback_xml, deposit.feedback_status AS deposit_feedback_status, deposit.feedback_updated_at AS deposit_feedback_updated_at \nFROM deposit \nWHERE deposit.code = %(code_1)s \n LIMIT %(param_1)s'] [parameters: [{}]]
```

**Comment by fabiobatalha** [comment]
Se você reiniciar o stack os processos voltam a funcionar.

Mas tem esse problema de integridade de transacao entre as tasks.

**Comment by gustavofonseca** [comment]
Resolvido nos commits [47d59b3cdcc05d465702493572bc8582aabb1a8f, 51f6b974a74ce75162945271cd923446e2bbb0ff, f7d8f13524a5c23c557f49b8f3268eb7774aa2fe]
